version: '3.3'
services:
  db_mysql:
    restart: always      
    image: mysql:5.7
    container_name: mysql
    command: mysqld --user=root --verbose
    volumes:
     - ./mysql_init:/docker-entrypoint-initdb.d
     - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test@222"
      MYSQL_ROOT_PASSWORD: "root@222"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
