version: '3.3'
services:  
  nginx:
    restart: always      
    image: nginx:latest
    ports:
        - 80:80
    volumes:
       - ./nginx_home/conf.d/:/etc/nginx/conf.d/
       - ./nginx_home/nginx.conf/:/etc/nginx/nginx.conf  
       - ./nginx_home/log/:/var/log/nginx/  
       - ./nginx_home/public:/var/www/html/public       
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ulimits:
      nproc: 65535
    network_mode: host    

