version: '3.3'
services:
  redis:
    restart: always
    image: redis:5.0.6
    container_name: redis
    volumes:
     - ./data:/data
     - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --requirepass xed@redis@2020!
    ports:
      - "6479:6379"

